coveo:
  outputs:
    dev:
      account: nbyyuyo-yr29957
      database: COVEO
      password: Blablacar04040505*
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: LAURAHUDSON
      warehouse: COMPUTE_WH
  target: dev
