coveo:
  outputs:
    dev:
      account: --
      database: COVEO
      password: --
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: LAURAHUDSON
      warehouse: COMPUTE_WH
  target: dev
